### PR TITLE
Fix X-RateLimit headers handling when using CompositeDelayFunction

### PR DESCRIPTION
**Pull request by sklv-max**
1. Filtering out default durations in the CompositeDelayFunction.
2. Returning default duration from the CompositeDelayFunction instead of null.

## Description
Since RateLimitResetDelayFunction and RetryAfterDelayFunction are returning `Duration.ofMinutes(-1)` instead of null as the default value since Riptide 4, it is needed to check not only for non-null values but also if there are any non-default delays in the CompositeDelayFunction.

## Motivation and Context
1. In Riptide 4 the default value in RateLimitResetDelayFunction and RetryAfterDelayFunction was changed from null to `Duration.ofMinutes(-1)` [link](https://github.com/zalando/riptide/commit/6bf111c9dec8c8d23e501e19d0bac2838917d142)
2. Failsafe 2.x.x used both negative duration and null as default values ([link](https://javadoc.io/static/net.jodah/failsafe/2.4.4/index.html?net/jodah/failsafe/function/DelayFunction.html)) 
3. Failsafe 3.x.x mentions only negative values as default values [(link)](https://failsafe.dev/javadoc/core/dev/failsafe/DelayablePolicyBuilder.html#withDelayFn-dev.failsafe.function.ContextualSupplier-). If null is returned from delay function, it leads to NPE in the Failsafe.

As Riptide 4, if CompositeDelayFunction consists of two functions (A and B) and A returns default value and B returns a positive meaningful value, the default value would be taken since it is not null.
 
The issue is opened [here](https://github.com/zalando/riptide/issues/1671).

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.

### CODE REVIEW

**Comment by fatroom** [comment]
@sklv-max please verify your gpg key and sign commit: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by sklv-max** [comment]
> @sklv-max please verify your gpg key and sign commit: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Thank you for pointing out, have done that.

**Comment by fatroom** [comment]
👍

**Comment by puncleV** [comment]
👍

**Comment by fatroom** [comment]
Thank you for the contribution!

**Pull request merged**
