### PR TITLE
Revert "Bump spring.version from 4.1.6.RELEASE to 5.1.9.RELEASE"

### PR DESCRIPTION
**Pull request by whiskeysierra**
This reverts commit df88756495ccf3796c17c7685b2df903a3b41649.

## Motivation and Context

#758 was meant to stay.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
I can't find an enforcer rule to require a certain dependency. And by design I want my code to be binary compatible to Spring 4 and Spring 5, so an upgrade will always work.

I could tell dependabot not to update to 5.x, but that's still risky.

**Comment by fatroom** [comment]
What about setting separate set of test dependencies like I did with the #741 ? So we can have to test runs for spring 4 and another for spring 5?

**Comment by whiskeysierra** [comment]
I could configure dependabot with a file.

https://dependabot.com/docs/config-file/

**Comment by whiskeysierra** [comment]
> What about setting separate set of test dependencies like I did with the #741 ? So we can have to test runs for spring 4 and another for spring 5?

I used profiles for that but since my default is spring4 it can silently be upgraded and both are the same. I could have a separate profile or test execution which uses a hard coded spring4 version. That might work.

**Comment by whiskeysierra** [comment]
> I could have a separate profile or test execution which uses a hard coded spring4 version. That might work.

Mmh. Though about it some more and I don't believe it will work.

A separate test execution means I need to run all tests twice. A separate profile might force a specific spring version, but that would still work after someone changed the dependency version since I'm compatible.

**Comment by whiskeysierra** [comment]
👍

**Pull request merged**
