### PR TITLE
Workflow test

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by fatroom** [comment]
As far as I understood you'll need something like this instead of plugin: https://github.com/marketplace/actions/coveralls-github-action

**Comment by fatroom** [comment]
Seems my assumption that Jacoco producing LCOV files was wrong. 
According to https://github.com/trautonen/coveralls-maven-plugin you'll need to provide repoToken as `-DrepoToken=yourcoverallsprojectrepositorytoken` to `mvn coveralls:report` if you're running outside of traffic CI.

**Comment by whiskeysierra** [comment]
Yes, and they don't have proper support for jacoco right now. See https://github.com/coverallsapp/github-action/issues/22.

I don't want to expose the coveralls token publicly.

**Comment by fatroom** [comment]
You can encrypt coverall token, so I'm not sure what your concern about exposing it: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

**Comment by whiskeysierra** [comment]
I don't have access to the repo settings, otherwise I could set up the coveralls token as a secret and continue to use the coveralls maven plugin.

**Comment by whiskeysierra** [comment]
:+1:

**Pull request merged**
