### PR TITLE
Switched to star imports

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Motivation and Context

Nobody is reading it anyway. Therefore let's reduce it to a bare minimum.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by fatroom** [comment]
👍

**Comment by fatroom** [comment]
Out of curiosity, what IDE/Codestyle are you using?

**Comment by whiskeysierra** [comment]
> Out of curiosity, what IDE/

IntelliJ IDEA

> Codestyle are you using?

Until now I was always using the defaults, but I'm starting to customize.

**Comment by fatroom** [comment]
AFAIK default in Idea is to fold 3 or 5 imports, seems that codacy using similar config

**Comment by fatroom** [comment]
Additionally I would recommend to put this convention to CODESTYLE file, since it's differs from defaults to what most of the people accustomed to.

**Comment by whiskeysierra** [comment]
Not worth the trouble.

**Pull request closed without merging**
