### PR TITLE
Renamed metrics to micrometer

### LINKED ISSUE #700: Rename MetricsPlugin to MicrometerPlugin
## Context

- consistency with other plugins:
  - `FailsafePlugin` (not `CircuitBreakerPlugin`, `RetryPlugin` or `ResiliencePlugin`)
  - `LogbookPlugin` (not `LoggingPlugin`)
  - `OpenTracingPlugin` (not `TracingPlugin`)

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Motivation and Context

Fixes #700

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by fatroom** [comment]
Seems good, but worth to add mention about this change to migration guide as well

**Comment by whiskeysierra** [comment]
> Seems good, but worth to add mention about this change to migration guide as well

Done

**Comment by fatroom** [comment]
👍

**Comment by fatroom** [comment]
👍

**Pull request merged**
