### PR TITLE
Extract ThreadPoolExecutorBuilder to separate module

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Motivation and Context

Adds proper scale-first support for thread pools (not just for core-size=0) and makes the builder a dependency-free, reusable module. Even without Riptide.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by fatroom** [comment]
I'll take a look in coming days

**Comment by whiskeysierra** [comment]
@fatroom Any thoughts?

**Comment by fatroom** [comment]
@whiskeysierra lgtm. I'm thinking about merging and creating release 3.0 out of this. Any objections?

**Comment by whiskeysierra** [comment]
Technically it should be another RC...

**Comment by fatroom** [comment]
when release will happen?

**Comment by whiskeysierra** [comment]
Once we're confident 😁

**Comment by fatroom** [comment]
👍

**Pull request merged**
