### PR TITLE
Added riptide-soap module

### LINKED ISSUE #510: SOAP support
## Detailed Description

Add a new `riptide-soap` module that provides reusable type tokens/converters/routes/... to deal with SOAP requests, incl. marshalling/unmarshalling, handling of envelopes and faults.

## Context

We sometimes have to integrate against legacy SOAP web services and can't use Riptide to it's fullest potential. Right now we configure a client (using the spring boot starter) and use it to construct a customized WebServiceTemplate.

## Possible Implementation

- [x] `riptide-soap` module
- [ ] Possible [Banner](https://pixabay.com/photos/faucet-soap-hand-washing-fountain-1581573/)

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Motivation and Context

Fixes #510

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by lukasniemeier-zalando** [comment]
I see SOAP clients being configured like this

```
    @Bean
    public HttpClientCustomizer customerHttpClientCustomizer() {
        return builder -> builder.disableContentCompression()
                .setConnectionReuseStrategy(NoConnectionReuseStrategy.INSTANCE)
                .addInterceptorFirst(new HttpComponentsMessageSender.RemoveSoapHeadersInterceptor());
    }
```

I have also seen `WebServiceTransportException` being marked as transient

Worth to have these as defaults?

**Comment by whiskeysierra** [comment]
```java
/**
 * HttpClient {@link org.apache.http.HttpRequestInterceptor} implementation that removes {@code Content-Length} and
 * {@code Transfer-Encoding} headers from the request. Necessary, because some SAAJ and other SOAP implementations set these
 * headers themselves, and HttpClient throws an exception if they have been set.
 */
public static class RemoveSoapHeadersInterceptor implements HttpRequestInterceptor {

    @Override
    public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
        if (request instanceof HttpEntityEnclosingRequest) {
            if (request.containsHeader(HTTP.TRANSFER_ENCODING)) {
                request.removeHeaders(HTTP.TRANSFER_ENCODING);
            }
            if (request.containsHeader(HTTP.CONTENT_LEN)) {
                request.removeHeaders(HTTP.CONTENT_LEN);
            }
        }
    }
}
```

**Comment by whiskeysierra** [comment]
> setConnectionReuseStrategy(NoConnectionReuseStrategy.INSTANCE)

I find a lot of conflicting information on this:

- https://coderanch.com/t/222067/java/Connection-pooling-SOAPConnection-objects
- https://mkleine.de/blog/2015/03/12/soap-clients-und-connection-keep-alive/
- https://stackoverflow.com/questions/27484844/jax-ws-client-closes-tcp-connection-with-fin-ack
- https://github.com/javaee/metro-jax-ws/issues/342
- https://connectedweb.wordpress.com/2010/05/24/understanding-java-web-services-jax-ws-and-wsdl/ (uses keep-alive in examples)

**Comment by whiskeysierra** [comment]
My local tests using Sun's JAX-WS implementation reveal that connection keep alive doesn't create an issue, but streaming request bodies might be a problem since the server will receive partial/invalid requests then.

**Comment by whiskeysierra** [comment]
> disableContentCompression

I believe content compression (response) can be left enabled as well since the only issue I see would be logging, but logbook is running beforehand anyway.

**Comment by whiskeysierra** [comment]
Our implementation actually never sets `Content-Length` nor `Transfer-Encoding` so I believe we're good.

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Pull request merged**
