### PR TITLE
bugfix/add-spring2.x-place-holder-resolver

### LINKED ISSUE #488: SpringBoot2xSettingsParser fails to resolve placeholders
## Description
When using riptide 2.8.1, and defining scopes as follows 
```yaml
riptide:
  clients:
    user-detail:
      oauth.scopes: uid, ${SCOPE:service.read}
```
The scopes are read as is without being resolved!
With a bit of debugging it seems this line(https://github.com/zalando/riptide/blob/7ee3f0917b213303d93d36fdb9c0cba524897643/riptide-spring-boot-2.x-support/src/main/java/org/zalando/riptide/spring/SpringBoot2xSettingsParser.java#L24)
It constructs a binder with no PlaceHolderResolver.

### PR DESCRIPTION
**Pull request by mazenmelouk**
adds a placeholder resolver to spring 2.x binder
fixes #488

### CODE REVIEW

**Comment by whiskeysierra** [comment]
Can you add a test?

**Comment by whiskeysierra** [comment]
I believe you're missing an import somewhere. Also, does this need to be fixed for spring boot 1.x as well?

**Comment by whiskeysierra** [comment]
https://travis-ci.org/zalando/riptide/jobs/430404676

**Comment by mazenmelouk** [comment]
okai, do you see any other way of fixing it? Rather that having Spring boot 2 as dependency

**Comment by whiskeysierra** [comment]
Replaced by #499

**Pull request closed without merging**
