### PR TITLE
Added NIO support

### PR DESCRIPTION
**Pull request by whiskeysierra**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando @tkrop :+1::question:

**Comment by tkrop** [comment]
Looks good, but I will have a second look before I give my :+1:.

**Comment by tkrop** [comment]
I absolutely like this, but I'm missing the documentation :).

**Comment by whiskeysierra** [comment]
@tkrop I added a section to the README. Can you give me a 👍?

**Comment by tkrop** [comment]
With this explanation you have confused me - I can't figure out how to apply the feature to its core use case. I'm missing the motivation and explanation how the Async IO helps to implement processor intensive execution chains based on the common thread pool.

**Comment by whiskeysierra** [comment]
> I'm missing the motivation and explanation how the Async IO helps to implement processor intensive execution chains based on the common thread pool.

I'm just trying to offer it for those interested in it. I don't believe this library is the right place to motivate and advocate for non-blocking IO.

> I can't figure out how to apply the feature to its core use case.

You just need to configure an `AsyncClientHttpRequestFactory` implementation of your choice. What would you like to see?

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by tkrop** [comment]
@whiskeysierra Sorry for not responding faster.

I think, I would have liked to see a two sentence explanation how to make use of a common executor service to circumvent the [How to set an ideal thread pool size](https://jobs.zalando.com/tech/blog/how-to-set-an-ideal-thread-pool-size/) issue you referred to directly above.

In my opinion we should explain, that the core idea of the non-blocking IO support is a clear separation of *wait time* and *service time* handling to simplify thread pool sizing. This is done by combining the non-blocking IO request factory with a single(ton) processor-number-sized executor services for optimal proportion between memory consumption and thread starvation.

Besides, I find the table a bit confusing, because it is telling only have the story neglecting the `capture` extension. Doing so it only shows the trivial facts. In addition, it is not showing the most favorable usage option outlined above.

**Comment by whiskeysierra** [comment]
For non blocking IO you don't provide any executor to riptide at all. That's completely up to the implementation of the factory. The API doesn't actually allow you to specify an executor. The table is misleading there, agreed.

**Pull request merged**
